### PR TITLE
Split sentences feature

### PR DESCRIPTION
**Pull request by Siddhant-Ray**
Made some changes to the split_into_sentences method in utils.py, which makes it easier for users to use the package. Changes have been tested using test.py. Only changes are in these two files, nothing else. test.py is just for checking if the changes work. Unfortunately I missed cherry-picking the commit but shouldn't matter here.

### CODE REVIEW

**Comment by PinchOfData** [comment]
Hi Siddhant, 

Thanks for looking into this!

My point of view:
1. I agree it would be a convenient feature for split_into_sentences() to take care of NaNs. 
2. Regarding the new embeddings, I think they can prove valuable, but you should know @aplamada is currently refactoring the code for the embeddings, so there will be some coordination needed here.

On a more general note, our typical workflow takes the following form: 
- one change = one pull request
> It would be perfect if you could distinguish the embeddings part from the split_into_sentences() part. 
> The split_into_sentences() correction seems more straightforward to push to the master branch.
- We use `pytest` to make sure everything works OK (see [documentation](http://doc.pytest.org/en/latest/doctest.html)). @aplamada can tell you more about this.
- We usually document the reason behind the changes to a function in the issues/pull request rather than in the code. We limit comments in the code to the bare minimum for a coder to understand what's happening (often the code itself is enough!).

Feel free to drop me a line if anything is unclear.

Talk to you soon,

**Comment by aplamada** [comment]
Hi Siddhant,

Thanks for using the code and finding room for improvement - This is welcome!

> 2\. Regarding the new embeddings, I think they can prove valuable, but you should know @aplamada is currently 
refactoring the code for the embeddings, so there will be some coordination needed here.

Please have a look at the branch [embeddings_v2](https://github.com/relatio-nlp/relatio/blob/embeddings_v2/relatio/embeddings.py) for the way we want to organize the embeddings. The examples in the docstring are used as tests - https://docs.python.org/3/library/doctest.html - and they are integrated into pytest - please see [here](https://docs.pytest.org/en/6.2.x/doctest.html).

Nevertheless we have to add more tests and we will probably add the `tests` directory, where we will put what does not fit into a simple doctest.

**Comment by Siddhant-Ray** [comment]
Hi, thanks for this! So the split_into_sentences() is only in the utils.py
file and is the real change which I wanted to add. Since the embeddings is
something I was exploring, we don't have to add that and since it's in a
different file, shouldn't be a problem right?

Or do you want me to open a new PR with just the split into sentences
change?

Thanks,
Siddhant

**Comment by PinchOfData** [comment]
A new PR with just the split into sentences would be perfect. Thanks!

**Comment by Siddhant-Ray** [comment]
Submitted a new PR, closing this one.

**Pull request closed without merging**
