### PR TITLE
Dimension reduction of embeddings before clustering

### PR DESCRIPTION
**Pull request by shimkoji**
Writing codes for issue #75.

Adding an option (weight_by_frequency) for allowing duplicate entities for dimension reduction and clustering.

If weight_by_frequency is true, dimension reduction and clustering are conducted with duplicate entities (clustering is weighted by each frequency).
If weight_by_frequency is false, dimension reduction and clustering are conducted with unique entities.

I also added different PCA options: incremental PCA and weighted PCA

### CODE REVIEW

**Comment by PinchOfData** [comment]
Hi Shimpei, 

I went through the code. 

I have several comments (on different levels).
- `weight_by_frequency` is practical and well implemented, I would add this change.
- `PCA_type` appears more bug-prone. 

Let me explain:
- `IncrementalPCA` is suitable for very large datasets, but I doubt we could run `UMAP` and `HDBSCAN` / `KMeans` afterward anyway. Did you experiment with this with a large dataset? We need to try it on an application to understand if it would be useful. On the bright side, it is built in sklearn, so at least we know it's well implemented.
- I am more skeptical of `WPCA` for several reasons: (1) Does it perform better than `IncrementalPCA` for large datasets? (2) The code is not maintained (has not been changed since 2016) and is version 0.1.  Do we really want to add this as a dependency for relatio?

**Comment by shimkoji** [comment]
> IncrementalPCA is suitable for very large datasets, but I doubt we could run UMAP and HDBSCAN / KMeans afterward anyway. Did you experiment with this with a large dataset? We need to try it on an application to understand if it would be useful. On the bright side, it is built in sklearn, so at least we know it's well implemented.

I tried Incremental PCA with the news data that I used for my course project (about 40,000 sentences) and it successfully built the narrative network.

IPCA


> I am more skeptical of WPCA for several reasons: (1) Does it perform better than IncrementalPCA for large datasets? (2) The code is not maintained (has not been changed since 2016) and is version 0.1. Do we really want to add this as a dependency for relatio?

I also tried WPCA with the news data and it successfully worked. But, the narrative output seems to be not so different. So, I don't strongly think that WPCA should be added. On top of that, WPCA approach needs more time for both fitting the model and predicting + building a narrative network than IPCA approach.

WPCA

Screenshot 2022-07-16 at 12 38 12

**Comment by shimkoji** [comment]
I tried IPCA, WPCA, and PCA approaches for my rough draft. 
But, the kernel crashed during the Grid Search process with all approaches. So I set the parameters beforehand.

**Comment by PinchOfData** [comment]
Thanks for the additional details. It's looking good. OK, so as far as relatio is concerned, I would remove `WPCA` and only keep `IncrementalPCA`.

Since we have multiple PCA_types, perhaps we could make a more flexible `__init__` for `NarrativeModel()`. `pca_type` and `model_type` could be replaced by more intuitive arguments.

`pca_type="PCA"` would become `pca: Optional[str] = None`. If `None`, then no dimension reduction with PCA is performed. Otherwise, we do the PCA specified (e.g., `IncrementalPCA`, `PCA`).

`model_type="hdbscan'"` would become `clustering:Optional[str]=None`. If `None`, then we just apply the `deterministic` prediction. Otherwise, we do the clustering approach specified (e.g., `HDBSCAN`, `KMeans`).

Finally, we would add an argument `UMAP: bool = True`. If `False`, no dimension reduction with `UMAP`. Otherwise, we dimension-reduce.

The defaults for nice results out-of-the-box would probably be:
`pca: Optional[str] = 'PCA'`
`UMAP: bool = True`
`clustering:Optional[str]='hdbscan'`

> But, the kernel crashed during the Grid Search process with all approaches. So I set the parameters beforehand.

Yes, I encounter this problem too on larger datasets. We will need to come up with a more robust grid in the future. TBD.

**Pull request closed without merging**
